// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AddPartyloser","status":true,"description":"ver1.05 戦闘終了時にノートタグ記載のアクターを仲間にします。","parameters":{"animation":"0","text1":"が起き上がった。","text2":"は仲間になった。","textallow":"仲間にする","textforbid":"拒否する","enableonce":"true","validBattletest":"true","defaultallrate":"100"}}
];
